name = "Testing2"
author = "Exo"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ece35017a7c6a04a0473d2fe06b83278b77ee3b1ec8b618b97802e8d54912ef"

[versions]
fabric = "0.12.5"
minecraft = "1.18"
