name: build
on: [push, pull_request]
jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python3 ./utils/build.py --deps
      - name: Compile pyinstaller
        run:  python3 ./utils/build.py --pyinstaller
      - name: Compile cxfreeze
        run: python3 ./utils/build.py --cxfreeze
      - name: Upload pyinstaller
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}_packwiz_gui_pyinstaller
          path: pyinstaller/dist
      - name: Upload cxfreeze
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}_packwiz_gui_cxfreeze
          path: cxfreeze/build

      - name: Zip files for upload
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -a -cf ${{ runner.os }}_packwiz_gui_cxfreeze.zip cxfreeze/build && tar -a -cf ${{ runner.os }}_packwiz_gui_pyinstaller.zip pyinstaller/dist
      - name: Upload to github actions
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
                 ${{ runner.os }}_packwiz_gui_pyinstaller.zip
                 ${{ runner.os }}_packwiz_gui_cxfreeze.zip
          token: ${{ secrets.GITHUB_TOKEN }}
