name: cx_freeze
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install deps
        run: python3 -m pip install cx_freeze PyInstaller PySimpleGUI PySimpleGUIQt

      - name: Compile cxfreeze
        run: cxfreeze packwiz_gui.py

      - name: Upload cxfreeze artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: packwiz_gui-linux-cxfreeze
          path: ./build

      - name: Cleanup
        run: rm -r ./build

      - name: Compile pyinstaller
        run: pyinstaller packwiz_gui.py

      - name: Upload pyinstaller artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: packwiz_gui-linux-pyinstaller
          path: ./dist

  build-windows:
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install deps
        run: python3 -m pip install cx_freeze PyInstaller PySimpleGUI

      - name: Compile cxfreeze
        run: cxfreeze packwiz_gui.py

      - name: Upload cxfreeze artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: packwiz_gui-windows-cxfreeze
          path: ./build

      - name: Cleanup
        run: rm build -Recurse

      - name: Compile pyinstaller
        run: pyinstaller packwiz_gui.py

      - name: Upload pyinstaller artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: packwiz_gui-windows-pyinstaller
          path: ./dist
